(()=>{'use strict';
const $=s=>document.querySelector(s), table=$('#table'), status=$('#status'), count=$('#count'), logEl=$('#log'), recipesEl=$('#recipes'), goalEl=$('#goal');
const DEF={
  villager:['村民','🧑','工人'], armedVillager:['持矛村民','🧑‍🌾','士兵'], base:['营地','🏕️','基地'], barracks:['训练营','🏛️','建筑'], tower:['哨塔','🗼','防御'], warehouse:['仓库','📦','建筑'], warband:['远征小队','🛡️','军队'], coast:['海岸','🏖️','地图'], clue:['雾岛线索','🗺️','线索'], fogGate:['雾岛入口','🌫️','地图'], boss:['雾岛巨兽','🐉','最终Boss'],
  bush:['莓丛','🌿','资源点'], forest:['树林','🌲','资源点'], quarry:['矿脉','⛰️','资源点'], berry:['莓果','🫐','食物'], bottle:['空瓶','🫙','材料'], jam:['莓酱','🍯','补给'], dough:['面团','🥟','材料'], tart:['莓塔','🧁','补给'], wood:['木头','🪵','资源'], stone:['石头','🪨','资源'], plank:['木板','🪚','建材'], stove:['炉灶','🔥','建筑'], festival:['节庆莓塔','🎂','高级补给'],
  gull:['海鸥盗贼','🕊️','野怪'], crab:['蟹壳兵','🦀','精英怪'], raider:['雾岛袭击者','👹','敌袭'], aiBase:['AI基地','🏰','AI'], aiWarband:['AI军队','⚔️','AI'], coin:['金币','🪙','货币'], pack:['海风补给包','🎁','卡包'], shell:['蟹壳','🐚','战利品'], spear:['木矛','🪵','武器'],
  merchantJam:['果酱商人','🧺','商人'], merchantStove:['炉灶商人','🧑‍🍳','商人'], merchantGuard:['守卫商人','🛡️','商人']
};
const STAGE_INTRO={1:'第1关：先学会采集、加工和造训练营。',2:'第2关：现在加入防守、仓库和第一个商人。',3:'第3关：海岸开放。把村民拖到海岸上，寻找雾岛线索。',4:'第4关：AI 基地出现，进入 1v1 对战。'};
const RES={bush:{out:'berry',uses:3,yield:1},forest:{out:'wood',uses:6,yield:1},quarry:{out:'stone',uses:4,yield:1}};
const STATS={villager:[1,2],armedVillager:[2,4],warband:[5,14],base:[0,10],tower:[2,8],gull:[1,2],crab:[3,5],raider:[2,3],boss:[3,10],aiWarband:[4,7],aiBase:[0,12]}, ENERGY_MAX=12;
const REC=[
  ['villager','forest','wood','伐木',{gather:true}], ['villager','quarry','stone','采矿',{gather:true}], ['villager','bush','berry','采集',{gather:true}], ['villager','coast','clue','探索海岸',{keep:['villager','coast']}], ['villager','clue','fogGate','定位雾岛',{keep:['villager']}], ['warband','fogGate','boss','引出Boss',{keep:['warband']}], ['wood','wood','plank','二合加工'], ['wood','stone','spear','锻造'], ['villager','spear','armedVillager','武装',{keep:['villager']}],
  ['berry','bottle','jam','补给'], ['jam','dough','tart','烘焙'], ['wood','stone','stove','建设'], ['stove','tart','festival','高级补给'], ['base','plank','barracks','建造训练营',{keep:['base']}], ['base','stone','tower','建造哨塔',{keep:['base']}], ['base','wood','warehouse','建造仓库',{keep:['base']}], ['barracks','armedVillager','warband','集结军队',{keep:['barracks','armedVillager']}]
];
const MERCHANTS={merchantJam:{need:['jam'],ability:'食物出售 +1 金币',text:'订单：交 1 个莓酱'},merchantStove:{need:['stove','tart'],ability:'补给制作有机会复制',text:'订单：交 炉灶 + 莓塔'},merchantGuard:{need:['shell','coin'],ability:'战斗胜利额外 +1 金币',text:'订单：交 蟹壳 + 金币'}};
let cards=[],known=new Set(),revealed=new Set(),unlocked=[],log=[],drag=null,bossDefeated=false,aiDefeated=false,baseHp=5,raid=4,raidNo=0,cap=22,stage=1,aiClock=4,enemyStep=0;
function uid(){return Math.random().toString(36).slice(2,8)}
function card(type,x,y,extra={}){let s=STATS[type];return {id:uid(),type,x,y,...(s?{hp:s[1]}:{}),...extra}}
function fresh(){cards=[card('base',65,80,{hp:10}),card('villager',210,80,{energy:ENERGY_MAX}),card('forest',360,85,{uses:6})];known=new Set();revealed=new Set(['base','villager','forest']);unlocked=[];bossDefeated=false;aiDefeated=false;baseHp=5;raid=4;raidNo=0;cap=22;stage=1;aiClock=4;enemyStep=0;log=[STAGE_INTRO[1],'连续点击树林，村民会消耗精力并喷出木头。'];drag=null;status.textContent='狂点资源点采集。每次点击都会喷出资源，并消耗村民精力。';render()}
function recipe(a,b){return REC.find(r=>(r[0]===a&&r[1]===b)||(r[0]===b&&r[1]===a))}
function addLog(t){log.unshift(t);log=log.slice(0,12)}
function has(t){return cards.some(c=>c.type===t)}
function addCard(t,x=120+Math.random()*520,y=220+Math.random()*260,extra){if(cards.length>=cap){status.textContent='桌面太满了。建仓库可以提高卡牌上限。';return null}let c=card(t,x,y,extra);cards.push(c);return c}
function worker(){return cards.find(c=>c.type==='villager')}
function reveal(t,x,y,extra){if(!revealed.has(t)){revealed.add(t);addCard(t,x,y,extra);addLog(`新内容开放：${DEF[t][0]}。`)}}
function revealStage(){if(stage>=1&&known.has('wood'))reveal('quarry',520,85,{uses:4});if(stage>=2){reveal('bush',610,90,{uses:3});reveal('bottle',760,95);reveal('merchantJam',560,500);reveal('gull',780,300)}if(stage>=3){reveal('coast',90,360);reveal('crab',790,300);reveal('pack',980,300);reveal('dough',920,95);reveal('merchantStove',700,500);reveal('merchantGuard',840,500)}}
function tick(){if(stage===4&&!aiDefeated){aiClock--; if(aiClock<=0){aiClock=4; if(!has('aiWarband')){cards.push(card('aiWarband',840,150)); addLog('AI 出兵：AI 军队集结。');} else if(!has('tower')){baseHp--; addLog(`AI 进攻：营地受损，生命 ${baseHp}/5。`); status.textContent='AI 正在进攻你的基地。'; if(baseHp<=0){status.textContent='AI 1v1 失败。你的基地被打爆了。'; return;}}}} if(bossDefeated||stage<2)return; raid--; if(raid<=0){raidNo++; if(has('tower')){let tower=cards.find(c=>c.type==='tower'); addLog(`敌袭 ${raidNo}：哨塔击退了袭击者。`); status.textContent='敌袭来了，但哨塔自动防守成功。'; tower.x+=4; tower.y+=2}else{baseHp--; addCard('raider',930,110+raidNo*30); addLog(`敌袭 ${raidNo}：营地受损，生命 ${baseHp}/5。建哨塔可自动防守。`); status.textContent=baseHp<=0?'营地被攻破。重开后优先建哨塔。':'敌袭造成营地受损。'} raid=4}}
function playerStep(){if(stage<2)return; enemyStep++; if(enemyStep>=2){enemyStep=0; enemyAttack()}}
function enemyAttack(){let enemy=cards.find(c=>['raider','gull','crab','aiWarband'].includes(c.type)); if(!enemy)return; let target=cards.find(c=>c.type==='tower')||cards.find(c=>['armedVillager','warband','villager'].includes(c.type))||cards.find(c=>c.type==='base'); if(!target)return; let atk=STATS[enemy.type]?.[0]||1; target.hp=(target.hp??(STATS[target.type]?.[1]||10))-atk; addLog(`敌方行动：${DEF[enemy.type][0]}攻击${DEF[target.type][0]}，造成 ${atk} 伤害。`); if(target.type==='base')baseHp=Math.max(0,baseHp-1); if(target.hp<=0){cards=cards.filter(c=>c.id!==target.id); addLog(`${DEF[target.type][0]}被击毁。`)} }
function hasNeeds(need){let pool=cards.map(c=>c.type);return need.every(n=>{let i=pool.indexOf(n);if(i<0)return false;pool.splice(i,1);return true})}
function packOpen(a,b){let coin=a.type==='coin'?a:b, pack=a.type==='pack'?a:b;if(!coin||!pack)return false;cards=cards.filter(c=>c.id!==coin.id&&c.id!==pack.id);[['forest',pack.x-80,pack.y+20,{uses:6}],['quarry',pack.x+30,pack.y+20,{uses:4}],['bush',pack.x+140,pack.y+20,{uses:3}]].forEach(x=>addCard(x[0],x[1],x[2],x[3]));addCard('pack',pack.x,pack.y+170);known.add('pack');addLog('购买：金币打开海风补给包，获得树林、矿脉、莓丛，并刷新一个补给包。');status.textContent='经济循环成立：战斗得金币，金币买补给包扩张资源。';tick();render(true);return true}
function progressStage(){if(!bossDefeated&&stage===1&&has('barracks')&&has('armedVillager')){stage=2;addLog(STAGE_INTRO[2])} if(!bossDefeated&&stage===2&&has('tower')&&has('warehouse')&&unlocked.includes('merchantJam')){stage=3;addLog(STAGE_INTRO[3])} if(bossDefeated&&stage===3){stage=4;cards.push(card('aiBase',920,80),card('aiWarband',840,150));aiClock=4;addLog(STAGE_INTRO[4])} revealStage()}
function fulfill(merchant){let spec=MERCHANTS[merchant.type];if(!spec)return false;if(unlocked.includes(merchant.type)){status.textContent='这个商人的能力已经解锁。';return true}if(!hasNeeds(spec.need)){status.textContent=`${DEF[merchant.type][0]}需要：${spec.need.map(n=>DEF[n][0]).join(' + ')}。`;return false}for(const n of spec.need){let i=cards.findIndex(c=>c.type===n);cards.splice(i,1)}unlocked.push(merchant.type);cards=cards.filter(c=>c.id!==merchant.id);if(merchant.type==='merchantJam')addCard('coin',merchant.x,merchant.y);if(merchant.type==='merchantGuard')addCard('spear',merchant.x,merchant.y);addLog(`完成商人科技：${DEF[merchant.type][0]}，获得「${spec.ability}」`);progressStage();status.textContent=`科技解锁：${spec.ability}。`;tick();render(true);return true}
function isFighter(t){return t==='villager'||t==='armedVillager'||t==='warband'}
function isMonster(t){return t==='gull'||t==='crab'||t==='boss'||t==='raider'||t==='aiWarband'||t==='aiBase'}
function combat(a,b){let fighter=isFighter(a.type)?a:b, monster=isMonster(a.type)?a:b;if(!fighter||!monster)return false;if(monster.type==='aiBase'&&fighter.type!=='warband'){status.textContent='AI基地需要远征小队或更强军队。';render();return true}if(monster.type==='boss'&&fighter.type!=='warband'){status.textContent='Boss 需要远征小队。先造训练营，再用训练营 + 持矛村民集结军队。';render();return true}if((monster.type==='crab'||monster.type==='raider')&&fighter.type==='villager'){status.textContent='这个敌人需要武器。先做木矛，把村民升级为持矛村民。';render();return true}let fa=STATS[fighter.type]?.[0]||1,ma=STATS[monster.type]?.[0]||1;monster.hp=(monster.hp??STATS[monster.type]?.[1]??1)-fa;fighter.hp=(fighter.hp??STATS[fighter.type]?.[1]??1)-ma;addLog(`交战：${DEF[fighter.type][0]}造成 ${fa} 伤害，承受 ${ma} 伤害。`);if(monster.hp<=0){cards=cards.filter(c=>c.id!==monster.id);let reward=monster.type==='crab'?'shell':'coin';if(monster.type==='boss')bossDefeated=true;else if(monster.type==='aiBase')aiDefeated=true;else addCard(reward,monster.x+24,monster.y+24);if(unlocked.includes('merchantGuard')&&monster.type!=='boss')addCard('coin',monster.x+58,monster.y+45);addLog(monster.type==='boss'?'最终战：远征小队击败雾岛巨兽，基地胜利！':monster.type==='aiBase'?'1v1：远征小队摧毁了 AI 基地。':'战斗：'+DEF[fighter.type][0]+'击退'+DEF[monster.type][0]+'，获得'+DEF[reward][0]+'。');if(fighter.hp<=0){cards=cards.filter(c=>c.id!==fighter.id);addLog(`${DEF[fighter.type][0]}也在战斗中倒下。`)}status.textContent=monster.type==='boss'?'胜利！基地发展、敌袭防守和最终 Boss 闭环成立。':monster.type==='aiBase'?'1v1 对战胜利。你击败了 AI 基地。':`击败 ${DEF[monster.type][0]}！`;progressStage();playerStep();tick();render(true);return true}if(fighter.hp<=0){cards=cards.filter(c=>c.id!==fighter.id);status.textContent=`${DEF[fighter.type][0]}战斗后倒下了，${DEF[monster.type][0]}还剩 ${monster.hp} 血。`;tick();render(true);return true}status.textContent=`${DEF[monster.type][0]}还剩 ${monster.hp} 血，继续叠放即可追击。`;playerStep();tick();render(true);return true}
function clickGather(node){let now=Date.now();if(node.lastGather&&now-node.lastGather<250)return true;node.lastGather=now;if(!cards.some(c=>c.id===node.id))return true;let w=worker();if(!w){status.textContent='需要村民才能采集资源。';render();return true}if((w.energy??ENERGY_MAX)<=0){status.textContent='村民精力耗尽。先处理其他建设，之后再恢复精力。';render();return true}let spec=RES[node.type];w.energy=(w.energy??ENERGY_MAX)-1;node.uses=(node.uses??spec.uses)-1;node.drops=(node.drops||0)+1;let gap=150,dx=(node.drops-1)%3*128,dy=Math.floor((node.drops-1)/3)*165,dropX=node.x+gap+dx,dropY=node.y+dy;if(dropX+118>(table.clientWidth||1200))dropX=Math.max(8,node.x-gap-dx);addCard(spec.out,dropX,dropY);known.add(spec.out);revealStage();addLog(`采集：点击${DEF[node.type][0]}，喷出${DEF[spec.out][0]}，精力 ${w.energy}/${ENERGY_MAX}，剩余 ${node.uses} 次。`);if(node.uses<=0){cards=cards.filter(c=>c.id!==node.id);addLog(`${DEF[node.type][0]}被采空了。`)}status.textContent=`爽快采集：${DEF[node.type][0]}喷出${DEF[spec.out][0]}！继续点还能继续喷。`;playerStep();tick();render(true);return true}
function gather(a,b,r){let node=RES[a.type]?a:b;return clickGather(node)}
function tryStack(a,b){if((a.type==='coin'&&b.type==='pack')||(a.type==='pack'&&b.type==='coin'))return packOpen(a,b);if(MERCHANTS[a.type])return fulfill(a);if(MERCHANTS[b.type])return fulfill(b);if((isFighter(a.type)&&isMonster(b.type))||(isFighter(b.type)&&isMonster(a.type)))return combat(a,b);let r=recipe(a.type,b.type); if(!r){status.textContent=`${DEF[a.type][0]} + ${DEF[b.type][0]} 没反应。当前建议：${objective()}`; render(); return false} if(r[4]&&r[4].gather)return gather(a,b,r);
  let keep=new Set((r[4]&&r[4].keep)||[]);cards=cards.filter(c=>!(c.id===a.id&&!keep.has(a.type))&&!(c.id===b.id&&!keep.has(b.type))); let made=addCard(r[2],(a.x+b.x)/2+28,(a.y+b.y)/2+20); if(!made)return false; known.add(r[2]); if(r[2]==='warehouse'){cap+=8;addLog('仓库建成：卡牌上限 +8。')} if(r[2]==='tower')addLog('哨塔建成：下一次敌袭会自动防守。'); if(r[2]==='tart'&&unlocked.includes('merchantStove')){addCard('tart',made.x+35,made.y+20);addLog('炉灶商人科技触发：补给制作额外复制 1 个莓塔。')} addLog(`发现：${DEF[r[0]][0]} + ${DEF[r[1]][0]} → ${DEF[r[2]][0]}（${r[3]}）`); progressStage(); status.textContent=`新卡：${DEF[r[2]][0]}。基地功能更完整。`; playerStep(); tick(); render(true); return true}
function hitCard(x,y,except){return cards.slice().reverse().find(c=>c.id!==except&&x>=c.x&&x<=c.x+118&&y>=c.y&&y<=c.y+156)}
	function startDrag(e,id){let c=cards.find(x=>x.id===id); if(!c)return; let r=table.getBoundingClientRect(); drag={id,dx:e.clientX-r.left-c.x,dy:e.clientY-r.top-c.y,startX:e.clientX,startY:e.clientY,moved:false,resource:!!RES[c.type]}; status.textContent=RES[c.type]?`点击 ${DEF[c.type][0]} 采集，或拖动它整理桌面。`:`拖动 ${DEF[c.type][0]}，松手叠到另一张卡上。`; e.currentTarget.setPointerCapture?.(e.pointerId)}
	function moveDrag(e){if(!drag)return; let c=cards.find(x=>x.id===drag.id); if(!c)return; if(!drag.moved&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<6)return; drag.moved=true; let r=table.getBoundingClientRect(); c.x=Math.max(8,e.clientX-r.left-drag.dx); c.y=Math.max(8,e.clientY-r.top-drag.dy); render()}
	function endDrag(){if(!drag)return; let c=cards.find(x=>x.id===drag.id),was=drag; if(!c){drag=null;return} if(was.resource&&!was.moved){drag=null;clickGather(c);return} let target=hitCard(c.x+59,c.y+78,c.id); drag=null; if(target)tryStack(c,target); else {status.textContent=was.resource?'已移动资源点。':'没有叠到卡上。拖到另一张卡中央再松手。'; render()}}
function objective(){if(stage===4){if(aiDefeated)return '第4关完成：你已经击败 AI 基地。'; if(!has('warband'))return '第4关：先集结远征小队，再去打 AI 基地。'; if(has('warband')&&!cards.some(c=>c.type==='aiBase'))return '第4关：等待 AI 基地出现。'; return '第4关：击败 AI 基地，完成 1v1。'} if(bossDefeated)return '已胜利。可以重开尝试更快路线。'; if(baseHp<=0)return '营地被攻破。重开后优先建哨塔。'; if(stage===1){if(!known.has('wood'))return '第1关：连续点击树林，村民会消耗精力并喷出木头。'; if(!has('barracks'))return '第1关：把两个木头叠在一起做木板，再把营地拖到木板上建训练营。'; if(!has('armedVillager'))return '第1关：做木矛，再把村民拖到木矛上。'; return '第1关完成，继续下一关。';} if(stage===2){if(!has('tower'))return '第2关：先建哨塔，挡住敌袭。'; if(!has('warehouse'))return '第2关：再建仓库，提高容量。'; if(!has('merchantJam'))return '第2关：完成果酱商人订单，解锁经济科技。'; return '第2关完成：海岸已开放。把村民拖到海岸上，寻找雾岛线索。';} if(stage===3){if(!known.has('clue'))return '第3关：把村民拖到海岸上，找到雾岛线索。'; if(!known.has('fogGate'))return '第3关：把村民拖到雾岛线索上，定位雾岛入口。'; if(!has('warband'))return '第3关：把训练营拖到持矛村民上，集结远征小队。'; if(!has('boss'))return '第3关：把远征小队拖到雾岛入口上，引出 Boss。'; return '第3关完成，去打 Boss。';} return '把远征小队拖到雾岛巨兽上，完成最终战。'}
function recipeTips(t){let tips=REC.filter(r=>r[0]===t||r[1]===t).map(r=>`${DEF[r[0]][0]} + ${DEF[r[1]][0]} → ${DEF[r[2]][0]}`);if(MERCHANTS[t])tips.push(`${DEF[t][0]}需要：${MERCHANTS[t].need.map(n=>DEF[n][0]).join(' + ')}`);return tips.join('\n')||'暂无已知用途，继续探索。'}
function label(c){let d=DEF[c.type],m=MERCHANTS[c.type],extra=''; if(RES[c.type])extra=`点击采集 · 剩 ${c.uses??RES[c.type].uses}`; if(m)extra=m.text; let stat=STATS[c.type]?`<span class="stats">攻 ${STATS[c.type][0]} · 血 ${c.hp??STATS[c.type][1]}/${STATS[c.type][1]}</span>`:''; if(c.type==='villager')stat+=`<span class="stats energy">精力 ${c.energy??ENERGY_MAX}/${ENERGY_MAX}</span>`; return `<span class="help" title="${recipeTips(c.type)}">?</span><span class="icon">${d[1]}</span><span class="name">${d[0]}</span>${stat}<span class="type">${extra||d[2]}</span>`}
	function render(pop=false){if(goalEl)goalEl.textContent=objective(); table.innerHTML=''; for(const c of cards){let d=DEF[c.type],m=MERCHANTS[c.type],el=document.createElement('button');el.className='card '+(m?'merchant ':'')+(isMonster(c.type)?'danger ':'')+(['spear','armedVillager','warband'].includes(c.type)?'weapon ':'')+(['base','barracks','tower','warehouse'].includes(c.type)?'basecard ':'')+(c.type==='coast'?'coastcard ':'')+(drag&&drag.id===c.id?'dragging ':'')+(pop&&c===cards[cards.length-1]?'new':'');el.style.left=c.x+'px';el.style.top=c.y+'px';el.innerHTML=label(c);el.onpointerdown=e=>startDrag(e,c.id);el.onpointermove=moveDrag;el.onpointerup=endDrag;el.onpointercancel=endDrag;table.append(el)} count.textContent=`第 ${stage} 关 · 营地 ${baseHp}/5 · 敌袭 ${raid} 步 · 容量 ${cards.length}/${cap} · Boss ${bossDefeated?'已击败':'未击败'}`; if(aiDefeated) status.textContent='胜利！你完成了堆叠大陆版 RTS 的 1v1 对战。'; else if(bossDefeated&&stage<4) status.textContent='胜利！这是带资源循环和基地压力的堆叠大陆版 RTS。'; logEl.innerHTML=log.map(x=>`<li>${x}</li>`).join(''); recipesEl.innerHTML=(REC.filter(r=>known.has(r[2])).map(r=>`<div class="recipe">${DEF[r[0]][0]} + ${DEF[r[1]][0]} → ${DEF[r[2]][0]}</div>`).join('')||'<div class="recipe unknown">发现配方后会记录在这里</div>')+'<h2>已解锁科技</h2>'+unlocked.map(t=>`<div class="recipe">${DEF[t][0]}：${MERCHANTS[t].ability}</div>`).join('')}
$('#restart').onclick=fresh; window.__funDebug={fresh,getState:()=>({cards:cards.map(c=>c.type),known:[...known],unlocked:[...unlocked],bossDefeated,aiDefeated,baseHp,raid,cap,stage,energy:worker()?.energy,log:[...log],status:status.textContent,goal:goalEl?.textContent}),clickType:t=>{let c=cards.find(c=>c.type===t);if(!c)throw new Error('missing card '+t);if(!RES[c.type])throw new Error('not resource '+t);c.lastGather=0;clickGather(c)},dragTypes:(a,b)=>{let matches=cards.filter(c=>c.type===a),ca=matches[0],cb=a===b?matches[1]:cards.find(c=>c.type===b);if(!ca||!cb)throw new Error('missing card '+a+' '+b);ca.x=cb.x+12;ca.y=cb.y+10;tryStack(ca,cb)}}; fresh(); if(new URLSearchParams(location.search).has('acceptance')){[['click','forest'],['click','forest'],['click','forest'],['click','forest'],['drag','wood','wood'],['drag','base','plank'],['click','quarry'],['click','quarry'],['drag','wood','stone'],['drag','villager','spear'],['drag','base','stone'],['drag','base','wood'],['click','bush'],['drag','berry','bottle'],['drag','jam','merchantJam'],['drag','villager','coast'],['drag','villager','clue'],['drag','barracks','armedVillager'],['drag','warband','fogGate'],['drag','warband','boss'],['drag','warband','boss'],['drag','warband','aiBase'],['drag','warband','aiBase'],['drag','warband','aiBase']].forEach(s=>s[0]==='click'?window.__funDebug.clickType(s[1]):window.__funDebug.dragTypes(s[1],s[2]));}
})();
